stages:
  - install
  - lint
  - test
  - build

variables:
  WORKDIR: frontend-angular
  NODE_VERSION: "20"

cache:
  key: "node-${CI_COMMIT_REF_SLUG}"
  paths:
    - ${WORKDIR}/node_modules

.install_base:
  image: node:${NODE_VERSION}
  before_script:
    - cd ${WORKDIR}
    - npm ci

install:
  stage: install
  extends: .install_base
  script:
    - node -v

lint:
  stage: lint
  extends: .install_base
  script:
    - npm run lint

test:
  stage: test
  image: node:${NODE_VERSION}
  before_script:
    - cd ${WORKDIR}
    - apt-get update && apt-get install -y chromium
    - export CHROME_BIN=/usr/bin/chromium
    - npm ci
  script:
    - npm run test:headless

build:
  stage: build
  extends: .install_base
  script:
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - ${WORKDIR}/dist
    expire_in: 7 days
