DROP TABLE STARTER_PERSON CASCADE CONSTRAINTS;
DROP TABLE STARTER_CITY CASCADE CONSTRAINTS;
DROP TABLE STARTER_COUNTRY CASCADE CONSTRAINTS;
DROP TABLE STARTER_CONTINENT CASCADE CONSTRAINTS;

DROP SEQUENCE STARTER_PERSON_ID_SEQ;
DROP SEQUENCE STARTER_CITY_ID_SEQ;
DROP SEQUENCE STARTER_COUNTRY_ID_SEQ;
DROP SEQUENCE STARTER_CONTINENT_ID_SEQ;
